# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'
services:
  dockovpn:
    image: alekslitvinenk/openvpn
    cap_add:
        - NET_ADMIN
    ports:
        - 8080:8080/tcp
    environment:
        HOST_ADDR: 0.0.0.0 
    volumes:
        - ./openvpn_conf:/doc/Dockovpn
    restart: always
